version: '3.7'
services:
  db:
    image: mongo
    container_name: roshi_db
    restart: always
    ports:
      - 2020:27017
    volumes:
      # - ./packages/db/data:/data/db # adds data persistence
      - ./packages/db/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: kamehouse
    command: --smallfiles

  server:
    build:
      context: ./packages/server
    env_file: ./packages/server/.env
    container_name: roshi_server
    depends_on:
      - db
    volumes:
      - ./packages/server:/usr/src/server
      - /usr/src/server/node_modules
    ports:
      - 3030:4000
    command: npm run dev

  ui:
    build:
      context: ./packages/ui
    container_name: roshi_ui
    volumes:
      - ./packages/ui:/usr/src/ui
      - /usr/src/ui/node_modules
    ports:
      - 4040:3000
    command: npm run dev

  # admin:
  #   build:
  #     context: ./packages/admin
  #   container_name: roshi_admin
  #   depends_on:
  #     - server
  #     - ui
  #   volumes:
  #     - ./packages/admin:/usr/src/admin
  #     - /usr/src/admin/node_modules
  #   ports:
  #     - 5050:3000

  site:
    build:
      context: ./packages/site
    container_name: roshi_site
    depends_on:
      - server
      - ui
    volumes:
      - ./packages/site:/usr/src/site
      - /usr/src/site/node_modules
    ports:
      - 6060:3000
    command: npm run dev

  clientweb:
    build:
      context: ./packages/client/web
    container_name: roshi_clientweb
    depends_on:
      - server
      - ui
    volumes:
      - ./packages/client/web:/usr/src/clientweb
      - /usr/src/clientweb/node_modules
    ports:
      - 7070:3000
    command: npm run dev
