version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: roshi_db
    restart: always
    ports:
      - 2020:27017
    volumes:
      # - ./packages/db/data:/data/db # adds data persistence
      - ./packages/db/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: kamehouse
    command: --smallfiles

  server:
    build:
      context: ./packages/server
    env_file: ./packages/server/.env
    container_name: roshi_server
    ports:
      - 3030:4000
    volumes:
      - ./packages/server:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run dev

  site:
    build:
      context: ./packages/site
    container_name: roshi_site
    ports:
      - 4040:3000
    volumes:
      - ./packages/site:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  webclient:
    build:
      context: ./packages/client/web
    container_name: roshi_webclient
    ports:
      - 5050:3000
    volumes:
      - ./packages/client/web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    links:
      - server
    command: npm run dev
